import assert from 'node:assert/strict';
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {fileURLToPath, pathToFileURL} from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const {chromium} = await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const url = process.argv[2] || 'http://127.0.0.1:8769/projects/009-awesome-ceo/demo/';
const recordName = process.argv[3] || 'browser.json';
const capture = process.argv.includes('--screenshots');
const catalog = JSON.parse(await readFile(path.join(root, 'notes/catalog.json'), 'utf8'));
const source = await readFile(path.join(root, 'notes/evidence/upstream-readme.md'), 'utf8');
const expectedCounts = {fundraising:24,entrepreneurship:12,product:6,sales:1,marketing:5,management:12,hiring:3,finance:4,books:10,'more-links':6,other:2};
assert.equal(catalog.items.length,85);
const originalLinks = [];
let active = false;
for (const line of source.split(/\r?\n/)) {
  if (line.startsWith('## ')) active = !['Contents','License'].includes(line.slice(3));
  if (!active || !/^\s{0,1}[-*] /.test(line)) continue;
  const clean = line.replace(/\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)/g,'').replace(/!\[[^\]]*\]\([^)]*\)/g,'');
  originalLinks.push([...clean.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g)].map(m=>({label:m[1],url:m[2]})));
}
assert.deepEqual(catalog.items.map(i=>i.links),originalLinks);
assert.equal(new Set(catalog.items.map(i=>i.id)).size,85);
assert.equal(catalog.items.filter(i=>i.authorNote).length,13);
assert.ok(catalog.items.every(i=>/[\u4e00-\u9fff]/.test(i.title)&&/[\u4e00-\u9fff]/.test(i.summary)));
const browser = await chromium.launch({headless:true,channel:'msedge'});
const page = await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const errors = [], checks = ['中文标题与导读完整；逐条原始标题和86个内容链接与固定快照一致'];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const visible = () => page.locator('.resource:visible').count();
try {
  assert.equal((await page.goto(url)).status(),200);
  assert.equal(await page.locator('.project-summary article').count(),3);
  assert.match(await page.locator('.project-summary').textContent(),/直接参考价值较低/);
  assert.match(await page.locator('.project-summary').textContent(),/融资、创业、产品、销售、营销、管理、招聘、财务/);
  await page.locator('#understanding-map').evaluate(img=>img.decode());
  assert.ok(await page.locator('#understanding-map').evaluate(img=>img.naturalWidth)>1000);
  assert.equal(await visible(),85);
  assert.equal(await page.locator('.resource-link').count(),86);
  assert.equal(await page.locator('.author-note').count(),13);
  const domLinks = await page.locator('.resource-link').evaluateAll(links=>links.map(a=>a.getAttribute('href')));
  assert.deepEqual(domLinks,catalog.items.flatMap(i=>i.links.map(l=>l.url)));
  assert.equal(await page.locator('h1').count(),1);
  assert.equal(await page.locator('.category-section').count(),11);
  checks.push('能力、资料范围和使用意义三段摘要；默认完整展示85条资源、11个分区、13处附注；所有内容链接与数据对应');
  if(capture) await page.screenshot({path:path.join(root,'assets/cover.png')});
  for(const [group,count] of Object.entries({reading:45,'books-courses':11,directories:13,cases:6,frameworks:4,practical:6})) {
    await page.locator(`[data-group="${group}"]`).click();
    assert.equal(await visible(),count,group);
    await page.reload(); assert.equal(await visible(),count);
  }
  await page.locator('#kind').selectOption('书籍');assert.equal(await visible(),9);
  await page.locator('[data-filter="all"]').click();
  checks.push('概念图加载、六组类型数量45/11/13/6/4/6、类型分组刷新与细分切换');
  for(const [category,count] of Object.entries(expectedCounts)) {
    await page.locator(`[data-filter="${category}"]`).click();
    assert.equal(await visible(),count,category);
    assert.equal(await page.locator('[data-section]:visible').count(),1);
  }
  checks.push('11个分类筛选数量逐项验证');
  await page.locator('[data-filter="all"]').click();
  await page.locator('#search').fill('客户');
  assert.ok(await visible()>0 && await visible()<85);
  await page.locator('#search').fill('Paul Graham'); assert.equal(await visible(),1);
  await page.locator('#clear-search').click(); assert.equal(await visible(),85);
  await page.locator('#search').fill('Product-Market Fit'); assert.equal(await visible(),1);
  await page.reload(); assert.equal(await visible(),1);
  await page.locator('#reset').click();
  await page.locator('#kind').selectOption('书籍'); assert.equal(await visible(),9);
  await page.locator('#search').fill('xxxxxxxxxx'); assert.equal(await visible(),0);
  assert.equal(await page.locator('#empty').isVisible(),true);
  await page.locator('#empty-reset').click(); assert.equal(await visible(),85);
  checks.push('中文/英文/作者搜索、9本书筛选、交叉筛选、空状态与重置、刷新保持搜索');
  await page.locator('[data-filter="books"]').click();
  await page.locator('#r70 summary').click();
  assert.match(await page.locator('#r70 .author-note p:visible').textContent(),/个人责任/);
  await page.locator('[data-filter="entrepreneurship"]').click();
  assert.equal(await page.locator('#r34 .resource-link').count(),2);
  await page.reload(); assert.equal(await visible(),12);
  await page.locator('.topbar a[href="#overview"]').click();
  assert.equal(await page.locator('#overview').getAttribute('open'),'');
  assert.equal(await page.locator('.overview-item').count(),11);
  await page.locator('.overview-item[href="#category=sales"]').click(); assert.equal(await visible(),1);
  checks.push('原作者附注展开、双链接条目、分类刷新、分类汇总展开与跳转');
  await page.locator('[data-filter="all"]').click();
  await page.locator('#overview').evaluate(d=>d.open=false);
  for(const width of [390,320]) {
    await page.setViewportSize({width,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);
    await page.locator('[data-filter="other"]').click(); assert.equal(await visible(),2);
    await page.locator('[data-filter="all"]').click();
  }
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  if(capture) await page.screenshot({path:path.join(root,'assets/mobile.png')});
  checks.push('390px与320px无横向溢出，手机分类筛选正常');
  await page.setViewportSize({width:1440,height:1100});
  await page.locator('#search').focus(); await page.keyboard.type('讨论薪酬'); assert.equal(await visible(),1);
  await page.keyboard.press('Tab'); assert.equal(await page.evaluate(()=>document.activeElement.id),'clear-search');
  checks.push('搜索键盘操作与清空按钮焦点');
  await page.goto(new URL('overview.html',url).href);
  await page.locator('#map-image').evaluate(img=>img.decode());
  const initialWidth=await page.locator('#map-image').evaluate(img=>img.clientWidth);
  await page.locator('#zoom-in').click();
  assert.ok(await page.locator('#map-image').evaluate(img=>img.clientWidth)>initialWidth);
  await page.locator('#zoom-out').click();
  assert.equal(await page.locator('#map-image').evaluate(img=>img.clientWidth),initialWidth);
  await page.locator('#zoom-in').click();await page.locator('#fit').click();
  assert.equal(await page.locator('#map-image').evaluate(img=>img.clientWidth),initialWidth);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#zoom-in').click();
  assert.ok(await page.locator('#viewer').evaluate(el=>el.scrollWidth>el.clientWidth));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.getByRole('link',{name:'← 返回资料导航'}).click();
  assert.equal(await page.locator('#understanding-map').count(),1);
  checks.push('独立总览图放大、缩小、适应窗口、手机滚动与返回导航');
  assert.deepEqual(errors,[]);
  const nojs = await browser.newContext({javaScriptEnabled:false});
  const staticPage = await nojs.newPage(); await staticPage.goto(url);
  assert.equal(await staticPage.locator('.resource').count(),85);
  assert.equal(await staticPage.locator('.resource-link').count(),86);
  await nojs.close(); checks.push('禁用JavaScript仍可读取全部资源与原始链接；页面无脚本或资源错误');
  await mkdir(path.join(root,'notes/evidence'),{recursive:true});
  await writeFile(path.join(root,'notes/evidence',recordName),JSON.stringify({verifiedAt:new Date().toISOString(),url,checks,errors,resources:85,contentLinks:86,categories:11,translatedNotes:13,externalDestinationsTested:false},null,2)+'\n');
  console.log(JSON.stringify({result:'passed',checks},null,2));
} finally {await browser.close();}
