/* Original demonstration built following the pinned baoyu-design workflow.
   Articles are authored samples. No feed fetching or model call is simulated as real. */
const {useState,useEffect,useRef}=React;
const {Button,Tag}=window.__DS_NAMESPACE__;
const STORE='baoyu-design-reader-v1';
const ARTICLES=[
 {id:1,title:'把阅读，变成一场有意识的探索',subtitle:'从收藏到理解，让每一次阅读都有所留下。',category:'设计',minutes:6,color:'violet',cover:'READ / THINK',author:'拾页编辑部',body:['我们每天遇到的信息远多于能够认真阅读的内容。一个好的阅读空间，应该先帮助你选择，再让你安心读完。','将内容收进来只是第一步。为文章标记一个主题，写下一句自己的理解，再在需要时找回它，知识才会逐渐与你发生关系。','这个原型围绕三个动作展开：发现值得读的内容、留出不被打扰的阅读时间，以及把真正有用的想法保存下来。试着收藏这篇文章，或把它标为已读。']},
 {id:2,title:'界面里的留白，也是一种语言',subtitle:'让重要的内容被看见，让视线有地方停留。',category:'设计',minutes:4,color:'lime',cover:'LESS, BUT / BETTER.',author:'拾页设计笔记',body:['留白不是页面剩余的空地，而是信息组织的一部分。距离会告诉读者哪些内容属于同一组，也能让操作之间的优先级更清楚。','当一个页面有太多边框、颜色和提示，读者需要先花力气理解界面，才能开始阅读。减少一种装饰，有时比添加一种效果更有效。','在右侧调整圆角和字号，观察同一份内容如何改变阅读节奏。切换到专注列表，还可以比较不同信息密度下的体验。']},
 {id:3,title:'一个设计系统，如何穿过不同页面',subtitle:'颜色与组件保持一致，表达依然可以丰富。',category:'工程',minutes:7,color:'blue',cover:'BUILD / TOGETHER',author:'拾页工程笔记',body:['设计系统将颜色、间距和组件的约定保存为可复用的文件。这样，页面之间的共同点不用靠记忆维持。','本演示的按钮和标签来自同一个组件包。它由 baoyu-design 的原版编译脚本生成，再经导入脚本复制到演示目录。','当主题颜色改变时，组件读取相同的 CSS 变量，于是主按钮、分类标签和选中状态一起改变。结构和行为保持原样。']},
 {id:4,title:'从“看起来可以”到“真的能操作”',subtitle:'交互状态，是原型与静态画面之间的距离。',category:'灵感',minutes:5,color:'orange',cover:'MAKE IT / WORK.',author:'拾页实验记录',body:['静态设计让我们讨论视觉，交互原型让我们讨论行为。搜索没有结果时显示什么？收藏后按钮如何反馈？刷新页面后状态是否保留？','这些问题需要在实际操作中回答。因此，这个演示实现了本地搜索、收藏、阅读状态和文章新增。它们保存在当前浏览器，不会同步到服务器。','新增文章允许你输入标题与正文。链接只作为参考资料保存，不会自动抓取网页，也没有隐藏的 AI 摘要调用。']}
];
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORE)||'{}');return {saved:Array.isArray(s.saved)?s.saved:[],read:Array.isArray(s.read)?s.read:[],custom:Array.isArray(s.custom)?s.custom.filter(a=>a&&typeof a.id==='number'&&typeof a.title==='string'&&Array.isArray(a.body)):[],theme:['purple','blue','green'].includes(s.theme)?s.theme:'purple',variant:['magazine','focus','wireframe'].includes(s.variant)?s.variant:'magazine',radius:Number.isFinite(s.radius)?Math.max(0,Math.min(24,s.radius)):14,font:Number.isFinite(s.font)?Math.max(14,Math.min(20,s.font)):16};}catch{return {saved:[],read:[],custom:[],theme:'purple',variant:'magazine',radius:14,font:16}}}
const glyphs={book:<><path d="M3 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-3H3z"/><path d="M21 4h-6a3 3 0 0 0-3 3v14a4 4 0 0 1 4-3h5z"/></>,grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,star:<path d="m12 3 2.8 5.7 6.3.9-4.6 4.5 1.1 6.3-5.6-3-5.6 3 1.1-6.3L3 9.6l6.2-.9z"/>,check:<path d="m5 12 4 4L19 6"/>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></>,arrow:<><path d="M5 12h14m-6-6 6 6-6 6"/></>,sliders:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/></>,close:<path d="m6 6 12 12M6 18 18 6"/>,plus:<path d="M12 5v14M5 12h14"/>};
function Icon({name,size=18}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{glyphs[name]||glyphs.book}</svg>}
function Cover({article}){return <div className={'cover '+article.color} aria-hidden="true"><div className="cover-ring"/><div className="cover-block"/><span>{article.cover.split(' / ').map((v,i)=><React.Fragment key={v}>{i>0&&<br/>}{v}</React.Fragment>)}</span><small>SHIYE / {String(article.id).padStart(2,'0')}</small></div>}
function Dialog({title,onClose,children}){const ref=useRef();useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close()},[]);return <dialog ref={ref} className="dialog" onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current)onClose()}}><header><h2>{title}</h2><button className="icon-button" aria-label="关闭对话框" onClick={onClose}><Icon name="close"/></button></header>{children}</dialog>}
function currentPage(){const hash=location.hash.slice(1);return hash.startsWith('u-')?'principle':['prototype','system','slides','principle'].includes(hash)?hash:'principle';}
function App(){
 const [data,setData]=useState(loadState),[page,setPage]=useState(currentPage),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[add,setAdd]=useState(false),[tweaks,setTweaks]=useState(true),[toast,setToast]=useState(''),[storageError,setStorageError]=useState(false);
 const articles=[...ARTICLES,...data.custom];
 useEffect(()=>{try{localStorage.setItem(STORE,JSON.stringify(data));setStorageError(false)}catch{setStorageError(true)}},[data]);
 useEffect(()=>{const handler=()=>setPage(currentPage());window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast]);
 const update=(key,value)=>setData(s=>({...s,[key]:value}));
 function toggle(key,id){setData(s=>({...s,[key]:s[key].includes(id)?s[key].filter(x=>x!==id):[...s[key],id]}));}
 const visible=articles.filter(a=>(filter==='all'||(filter==='saved'?data.saved.includes(a.id):filter==='read'?data.read.includes(a.id):a.category===filter))&&(a.title+a.subtitle+a.category+a.body.join('')).toLowerCase().includes(query.toLowerCase()));
 const colors={purple:['#5144ce','#efedff'],blue:['#245ab9','#eaf1ff'],green:['#217153','#e7f4ed']}[data.theme];
 const style={'--accent':colors[0],'--accent-soft':colors[1],'--radius':data.radius+'px','--body-size':data.font+'px'};
 const tabs=[['principle','01','理解与原理'],['prototype','02','交互原型'],['system','03','设计系统'],['slides','04','演示文稿']];
 function addArticle(e){e.preventDefault();const form=new FormData(e.currentTarget);const title=form.get('title').trim(),body=form.get('body').trim();if(!title||!body){setToast('标题和正文不能为空');return;}const a={id:Date.now(),title,subtitle:body.slice(0,52),category:form.get('category'),minutes:Math.max(1,Math.ceil(body.length/300)),color:'violet',cover:'MY / NOTES',author:'我的文章',body:body.split(/\n+/),url:form.get('url').trim()};setData(s=>({...s,custom:[...s.custom,a]}));setFilter('all');setQuery('');setAdd(false);setToast('已保存到当前浏览器');}
 return <div style={style} className="lab"><a className="skip" href="#main">跳转到内容</a><header className="topbar"><a href="#principle" className="wordmark"><span className="brand-mark">b.</span><strong>baoyu<span> / design lab</span></strong></a><div className="top-meta"><span>开源能力实验 · 008</span><a href="https://github.com/JimLiu/baoyu-design" target="_blank" rel="noreferrer">上游仓库 ↗</a></div></header>
 <main id="main"><div className="intro"><div><div className="eyebrow">BAOYU-DESIGN / PROJECT GUIDE</div><h1>让 AI 按设计规范，完成多种设计成果。</h1><p>面向 AI 编程助手的设计 Skill 工具包：从界面原型、演示文稿到文档与可视化，共享设计规范、组件和交付工具。</p></div><div className="intro-note"><span className="status-dot"/>基于 baoyu-design 工作流制作<span className="subtle">原创演示 · 非上游操作后台</span></div></div>
 <nav className="tabs" aria-label="能力演示"><div>{tabs.map(([id,num,label])=><a key={id} href={'#'+id} className={page===id?'active':''} aria-current={page===id?'page':undefined}><span>{num}</span>{label}</a>)}</div><span className="tab-aside">一个需求，多种可交付成果</span></nav>
 {page==='prototype'&&<><div className="experiment-bar"><div className="variant-picker" aria-label="设计方向">{[['magazine','杂志卡片'],['focus','专注列表'],['wireframe','结构线框']].map(([id,label],i)=><button key={id} aria-pressed={data.variant===id} className={data.variant===id?'selected':''} onClick={()=>update('variant',id)}><span>{String.fromCharCode(65+i)}</span>{label}</button>)}</div><button className={'tweak-toggle '+(tweaks?'selected':'')} aria-expanded={tweaks} onClick={()=>setTweaks(!tweaks)}><Icon name="sliders"/>外观调校</button></div>
 <div className={'workspace '+(tweaks?'':'no-inspector')}><div className={'reader '+data.variant}><aside className="reader-sidebar"><div className="reader-brand"><span><Icon name="book" size={24}/></span><div><strong>拾页</strong><small>给想法一个归处</small></div></div><div className="sidebar-label">我的空间</div><nav aria-label="文章分类">{[['all','grid','全部文章',articles.length],['saved','star','我的收藏',data.saved.length],['read','check','已经读过',data.read.length]].map(([id,icon,label,count])=><button key={id} className={filter===id?'active':''} onClick={()=>{setFilter(id);setSelected(null)}}><Icon name={icon}/><span>{label}</span><small>{count}</small></button>)}</nav><div className="sidebar-label">主题合集</div><nav aria-label="主题">{['设计','工程','灵感'].map((v,i)=><button key={v} className={filter===v?'active':''} onClick={()=>{setFilter(v);setSelected(null)}}><span className={'topic-dot topic-'+i}/><span>{v}</span><small>{articles.filter(a=>a.category===v).length}</small></button>)}</nav><div className="sidebar-bottom"><div className="avatar">拾</div><div><strong>我的阅读空间</strong><small>仅在此浏览器保存</small></div></div></aside>
 <section className="reader-content"><header className="reader-top"><span>WORKSPACE <span className="slash">/</span> {filter==='all'?'全部文章':filter==='saved'?'我的收藏':filter==='read'?'已经读过':filter}</span><span className="local-badge">本地演示</span></header>
 {selected?<article className="article-detail"><button className="back-link" onClick={()=>setSelected(null)}>← 返回文章列表</button><div className="detail-meta"><Tag label={selected.category}/><span>{selected.minutes} 分钟阅读 · {selected.author}</span></div><h2>{selected.title}</h2><p className="detail-subtitle">{selected.subtitle}</p><div className="detail-body">{selected.body.map((p,i)=><p key={i}>{p}</p>)}</div>{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer">查看参考链接 ↗</a>}<div className="detail-actions"><Button label={data.saved.includes(selected.id)?'取消收藏':'收藏文章'} onClick={()=>toggle('saved',selected.id)}/><Button variant="secondary" label={data.read.includes(selected.id)?'标为未读':'标为已读'} onClick={()=>toggle('read',selected.id)}/>{data.custom.some(a=>a.id===selected.id)&&<Button variant="ghost" label="删除此文章" onClick={()=>{const id=selected.id;setData(s=>({...s,custom:s.custom.filter(a=>a.id!==id),saved:s.saved.filter(x=>x!==id),read:s.read.filter(x=>x!==id)}));setSelected(null);setToast('已删除这篇本地文章')}}/>}</div></article>:<><div className="collection-heading"><div><div className="eyebrow">YOUR DAILY INSPIRATION</div><h2>{filter==='all'?'值得慢慢读的，都在这里。':filter==='saved'?'留住那些有共鸣的想法。':filter==='read'?'每次读完，都有一点收获。':filter+'，值得再看一眼。'}</h2><p>{visible.length} 篇内容 · 不急着读完，先找到喜欢的。</p></div><Button label="＋ 添加文章" onClick={()=>setAdd(true)}/></div><label className="search"><Icon name="search"/><input aria-label="搜索文章" placeholder="搜索标题、主题或正文…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><Icon name="close" size={16}/></button>}<span>本地搜索</span></label>
 <div className="article-grid">{visible.map(a=><article className="article-card" key={a.id}><button className="cover-button" aria-label={'阅读：'+a.title} onClick={()=>setSelected(a)}><Cover article={a}/></button><div className="card-content"><div className="card-meta"><Tag label={a.category}/><span>{a.minutes} 分钟阅读</span></div><button className="article-title" onClick={()=>setSelected(a)}><h3>{a.title}</h3></button><p>{a.subtitle}</p><footer><span>{data.read.includes(a.id)?'✓ 已读':a.author}</span><button className={'save '+(data.saved.includes(a.id)?'is-saved':'')} aria-label={(data.saved.includes(a.id)?'取消收藏：':'收藏：')+a.title} aria-pressed={data.saved.includes(a.id)} onClick={()=>toggle('saved',a.id)}><Icon name="star"/></button></footer></div></article>)}</div>{!visible.length&&<div className="empty"><Icon name="book" size={36}/><h3>{query?'没有找到匹配内容':'这里还没有文章'}</h3><p>{query?'换个关键词，或清空筛选再看看。':filter==='saved'?'点击文章卡片的星标，把喜欢的内容留在这里。':'读完一篇文章，或添加自己的内容。'}</p><Button label="查看全部文章" variant="secondary" onClick={()=>{setFilter('all');setQuery('')}}/></div>}</>}
 <footer className="reader-footer"><span>SHIYE / A QUIETER PLACE TO READ</span><span>内容为原创演示样本</span></footer></section></div>
 {tweaks&&<aside className="inspector"><header><Icon name="sliders"/><strong>把它调成你的样子</strong></header><p>同一套内容与组件，实时探索不同表达。</p><div className="control-group"><label>品牌主色 <small>{colors[0].toUpperCase()}</small></label><div className="swatch-buttons">{[['purple','#5144ce','鸢尾紫'],['blue','#245ab9','探索蓝'],['green','#217153','森林绿']].map(([id,color,label])=><button key={id} style={{background:color}} aria-label={label} aria-pressed={data.theme===id} onClick={()=>update('theme',id)}>{data.theme===id&&<Icon name="check" size={17}/>}</button>)}</div></div><div className="control-group"><label htmlFor="radius">组件圆角 <small>{data.radius}px</small></label><input id="radius" type="range" min="0" max="24" value={data.radius} onChange={e=>update('radius',+e.target.value)}/><div className="range-label"><span>利落</span><span>柔和</span></div></div><div className="control-group"><label htmlFor="font">阅读字号 <small>{data.font}px</small></label><input id="font" type="range" min="14" max="20" value={data.font} onChange={e=>update('font',+e.target.value)}/><div className="range-label"><span>Aa</span><span className="big-aa">Aa</span></div></div><div className="sample-card"><Tag label="实时组件"/><p>Button & Tag</p><Button label="试试这个按钮" onClick={()=>setToast('此按钮来自上游编译器生成的组件包')}/></div><button className="reset" onClick={()=>setData(s=>({...s,theme:'purple',radius:14,font:16,variant:'magazine'}))}>恢复默认外观</button><div className="inspector-note"><strong>观察什么？</strong><p>主按钮、标签与选中状态一起变化，体现设计变量的统一复用。</p></div></aside>}</div><div className="under-workspace"><span><span className="status-dot"/>可操作：搜索、收藏、阅读、新增、刷新保留</span><span>试试先收藏一篇，再切换「我的收藏」。</span></div></>}
 {page==='system'&&<section className="exhibit"><div className="section-heading"><div><div className="eyebrow">ONE SYSTEM, MANY SCREENS</div><h2>把一致性，放进可复用的文件。</h2><p>按钮与标签经过原版编译器生成，再由原版导入工具绑定到这个演示。</p></div><a className="text-link" href="../code/reader-kit/preview.html" target="_blank" rel="noreferrer">打开完整组件预览 ↗</a></div><div className="system-layout"><div className="system-flow">{[['01','定义','15 个设计变量，2 个交互组件'],['02','编译','输出组件包、清单与检查规则'],['03','检查','上游只读检查器检查结构'],['04','复用','导入到项目，界面加载同一组件包']].map(([n,t,d])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div><div className="component-stage"><div className="eyebrow">LIVE COMPONENTS</div><h3>看得见，也能点的规范。</h3><div className="component-row"><Button label="主要操作" onClick={()=>setToast('主按钮已响应')}/><Button label="次级操作" variant="secondary" onClick={()=>setToast('次级按钮已响应')}/><Button label="禁用状态" disabled/></div><div className="component-row"><Tag label="设计"/><Tag label="辅助信息" tone="neutral"/><Tag label="已保存" tone="success"/></div><div className="token-grid">{[['主色',colors[0]],['文字','#222338'],['浅底',colors[1]],['画布','#f5f5fa']].map(([label,color])=><div key={label}><div style={{background:color}}/><span>{label}</span><code>{color}</code></div>)}</div><p className="fine-print">切回「交互原型」调整主色，组件在这里也会同步变化。</p></div></div><div className="evidence-banner"><Icon name="check"/><div><strong>有生成记录，可以回查</strong><p>组件不是手写成“编译结果”。源文件、生成清单和执行记录都保存在子项目中。</p></div><a href="../notes/evidence/upstream-tools.json" target="_blank">查看记录 ↗</a></div></section>}
 {page==='slides'&&<section className="exhibit"><div className="section-heading"><div><div className="eyebrow">A DECK IS ALSO A WEB PAGE</div><h2>把同一个想法，讲成一份演示。</h2><p>四页演示使用上游原版 deck-stage：翻页、全屏与分步动画。</p></div><a className="text-link" href="./deck.html" target="_blank" rel="noreferrer">独立窗口播放 ↗</a></div><iframe className="deck-frame" src="./deck.html" title="拾页阅读产品演示文稿" allow="fullscreen"/><div className="deck-bottom"><p>点击画面后，用 ← → 翻页；第三页按 → 依次展示三个步骤。按 F 全屏。</p><a className="download" href="./downloads/shiye-design.pptx" download>下载可编辑 PPTX ↓</a></div></section>}
 {page==='principle'&&<Understanding/>}
 <footer className="site-footer"><span>BAOYU-DESIGN / CAPABILITY STUDY</span><span>交互原型由本项目制作 · 组件工具与幻灯片舞台来自上游</span><a href="../README.md" target="_blank">项目说明 ↗</a></footer>
 </main>{storageError&&<div role="alert" className="storage-warning">浏览器不允许本地保存；当前仍可操作，刷新后改动可能丢失。</div>}{toast&&<div className="toast" role="status"><Icon name="check"/>{toast}</div>}
 {add&&<Dialog title="把值得读的内容留在这里" onClose={()=>setAdd(false)}><p className="dialog-note">手动输入演示文章，仅保存到当前浏览器。</p><form onSubmit={addArticle}><label>文章标题<input name="title" required maxLength="80" placeholder="一个值得记录的想法" autoFocus/></label><label>主题<select name="category"><option>设计</option><option>工程</option><option>灵感</option></select></label><label>参考链接（选填）<input name="url" type="url" pattern="https?://.*" placeholder="https://…"/></label><label>正文<textarea name="body" required maxLength="20000" rows="5" placeholder="粘贴正文，或记下你自己的理解…"/></label><p className="fine-print">参考链接仅作为链接保存，不会自动抓取网页。</p><button className="ds-button" type="submit">保存文章</button></form></Dialog>}
 </div>
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
