/* Original research guide. Task mappings are sourced from the pinned upstream;
 * grouping and explanations are our synthesis, not a live agent execution. */
function Understanding() {
 const [taskId,setTaskId]=React.useState('mobile-app-design');
 const [mapZoom,setMapZoom]=React.useState(100);
 React.useEffect(()=>{const id=location.hash.slice(1);if(id.startsWith('u-'))document.getElementById(id)?.scrollIntoView();},[]);
 const task=UNDERSTANDING.tasks.find(item=>item.id===taskId);
 const upstream='https://github.com/JimLiu/baoyu-design/blob/026d4ea012bdd5cada72ac8cc13f21ba4edf2245/skills/baoyu-design/';
 return <section className="exhibit understanding">
  <div className="section-heading"><div><div className="eyebrow">UNDERSTAND THE TOOLKIT</div><h2>给 AI 的设计工作流与工具包。</h2><p>从通用规范到专项细节，按目标组合 Skill；由现有 AI 助手调用模板与工具完成交付。</p></div><a className="text-link" href="../notes/understanding.md" target="_blank" rel="noreferrer">阅读完整理解文档 ↗</a></div>
  <section className="u-summary" aria-label="项目概要"><article><span>项目定位</span><h3>面向 AI 助手的设计 Skill 工具包</h3><p>将设计方法组织成可执行的工作指南，配套组件模板与工具，指导 AI 梳理需求、设计方案并制作成果。</p></article><article><span>支持目标</span><h3>从界面原型到多种视觉成果</h3><p>支持网页与移动端原型、线框图、设计系统、演示文稿、文档简历、图表、动画、3D、邮件与宣传单等任务。</p></article><article><span>工作原理</span><h3>通用规范与专项 Skill 按需组合</h3><p>AI 根据目标读取指南，以项目品牌和组件规范为共同依据，编写代码、调用工具，通过预览和检查迭代交付。</p></article><article><span>使用价值</span><h3>复用设计基础，保持成果一致</h3><p>把品牌、配色、字体与组件用于不同设计任务，减少重复描述和搭建，让成果便于修改、复用和多格式交付。</p></article></section>
  <div className="u-callout"><strong>你看到的是我们的研究网页，不是这个库自带的操作后台。</strong><p>“拾页”是本项目制作的产出示例。上游有组件、预览模板与工具，但没有完整的独立设计工作台；使用入口是你已有的 AI 助手。浏览本页不会调用 AI。</p></div>
  <nav className="u-jumps" aria-label="理解指南章节">{[['u-map','完整引导图'],['u-identity','本质与比较'],['u-targets','13 类任务'],['u-architecture','内部原理'],['u-unified','统一约束'],['u-catalog','53 份说明'],['u-rules','约束与边界']].map(([id,title])=><a key={id} href={'#'+id}>{title}</a>)}</nav>
  <section id="u-map" className="u-section"><div className="eyebrow">READING MAP / 全景导览</div><h3>从通用规则到专项细节，按需组合能力。</h3><p>共同流程提供基础要求，项目规范保持品牌一致，专项 Skill 适应不同成果，模板与脚本执行具体工作。阅读顺序：能力定位 → 产品目标 → 统一约束 → 执行机制 → 完整技能目录 → 对我们的意义。</p><div className="u-map-toolbar" role="group" aria-label="引导图查看工具"><button type="button" onClick={()=>setMapZoom(Math.max(100,mapZoom-50))} disabled={mapZoom===100} aria-label="缩小引导图">−</button><output aria-live="polite">{mapZoom}%</output><button type="button" onClick={()=>setMapZoom(Math.min(500,mapZoom+50))} disabled={mapZoom===500} aria-label="放大引导图">＋</button><button type="button" onClick={()=>setMapZoom(100)}>适合宽度</button><a href="../assets/understanding-map.png" target="_blank" rel="noreferrer">查看高清 PNG ↗</a><a href="../assets/understanding-map.svg" target="_blank" rel="noreferrer">可缩放 SVG ↗</a></div><figure className="u-map-figure"><div className="u-map-viewport" role="region" aria-label="完整引导图，可放大后滚动查看" tabIndex="0"><img src="../assets/understanding-map.png" alt="baoyu-design 完整理解引导图：13 类产品目标、五层统一约束、AI 执行过程、8 组共 53 份说明、研究意义和验证边界。全部内容另有本页文字说明。" style={{width:mapZoom+'%'}}/></div><figcaption>原创研究图，非上游产品截图。包含 53 个说明文件名及职责；手机上可先放大，再横向和纵向滚动。图中分类是我们的归纳，能力边界以固定版本和实测记录为准。</figcaption></figure></section>
  <section id="u-identity" className="u-section"><div className="eyebrow">01 / WHAT IT IS</div><h3>与前端 Skill 相比，多了任务组织和交付工具。</h3><div className="u-grid three">{[
   ['003 · Frontend Design Toolkit','资源导航与组合建议','我们研究的版本只有 README，主要帮助选工具；其中研究过的 frontend-design Skill 专注视觉设计指导。'],
   ['008 · baoyu-design','Skill 流程＋模板＋脚本','内部也有 frontend-design 说明；还组织资料导入、交互制作、设计系统、检查和格式导出。'],
   ['Claude Design','有操作界面的官方产品','部分任务目标相近，但交互界面与产品集成由官方提供。baoyu 是独立社区项目，不能由此推定能力完全等价。']
  ].map(([title,tag,desc])=><article key={title}><span className="u-tag">{tag}</span><h4>{title}</h4><p>{desc}</p></article>)}</div><p className="u-note">组织方式更像我们研究的 004 · ASu-skills：把领域流程、模板和工具交给宿主 AI 执行。002 偏通用开发实践，006 偏技能目录。<a href="https://claude.com/product/design" target="_blank" rel="noreferrer">Claude Design 官方说明 ↗</a></p></section>
  <section id="u-targets" className="u-section"><div className="eyebrow">02 / TASK ROUTING</div><h3>选择一个目标，看它怎样组合能力。</h3><p>13 类是上游的任务入口；一个入口可以组合多个 Skill，多个入口也可以复用同一份说明。</p><div className="u-task-layout"><div className="u-task-buttons" role="group" aria-label="13 类产品目标">{UNDERSTANDING.tasks.map(item=><button type="button" key={item.id} aria-pressed={item.id===taskId} aria-controls="u-task-detail" onClick={()=>setTaskId(item.id)}>{item.label}</button>)}</div><article id="u-task-detail" className="u-task-detail" aria-live="polite" aria-atomic="true"><span className="u-tag">源码能力入口 · 非全部实测</span><h4>{task.label}</h4><p>{task.description}</p><dl><dt>加载的 Skill</dt><dd>{task.skills.map(name=><a className="u-code-link" key={name} href={upstream+'built-in-skills/'+name+'.md'} target="_blank" rel="noreferrer">{name}</a>)}</dd><dt>配套模板</dt><dd>{task.starters.length?task.starters.join(' / '):'无指定起步模板'}</dd><dt>本次验证边界</dt><dd>{task.verification}</dd></dl></article></div><p className="u-note">同一个电商项目可以需要商品页原型、后台界面、组件规范和宣传 PPT；这里按成果形式划分，不按行业划分。<a href={upstream+'project-types.json'} target="_blank" rel="noreferrer">核对上游路由表 ↗</a></p></section>
  <section id="u-architecture" className="u-section"><div className="eyebrow">03 / HOW IT WORKS</div><h3>AI 负责组织执行，脚本负责具体操作。</h3><ol className="u-flow">{[
   ['识别任务','SKILL.md 指示 AI 判断任务，按需读取专项说明；不是固定程序自动调度所有步骤。'],
   ['加载上下文','总体工作规范＋当前助手的工具说明＋项目已有品牌和组件规范。'],
   ['制作产物','AI 编写 HTML / CSS / React，复用起步模板，按需调用编译或导入脚本。'],
   ['观察与修正','浏览器渲染页面；AI 结合报错、交互结果和可用的截图反馈继续修改。'],
   ['记录与交付','记录文件和版本，按需求调用 PPTX、PDF、视频等交付路径；需要的依赖必须可用。']
  ].map(([title,desc])=><li key={title}><h4>{title}</h4><p>{desc}</p></li>)}</ol><div className="u-grid two"><article><h4>项目规范也会变成 AI 的输入</h4><p>设计系统导入器复制实际组件，并生成 <code>_ds_prompt.md</code>：包含接入方法、组件使用说明和允许的样式变量。继续项目时，AI 根据 <code>_d_meta.json</code> 恢复绑定并读取这些规则。</p></article><article><h4>文档名称不等于执行权限</h4><p><code>system-prompt.md</code> 是助手读取的文件，不会因名字自动获得平台最高指令优先级。<code>agents/</code> 同时放脚本和检查说明，也不等于运行着一组自主智能体。</p></article></div></section>
  <section id="u-unified" className="u-section"><div className="eyebrow">04 / SHARED RULES, SPECIALIZED DETAILS</div><h3>统一做事方式和品牌依据，按目标细化实现。</h3><p>这是一套从通用到专项的分层指南，也是一套横向组合的能力集合。做手机原型时，会一起使用移动端、高保真、交互和设计系统相关说明；不会把所有 Skill 都执行一遍。</p><ol className="u-unified-layers">{[
   ['共同工作流程','system-prompt.md','先理解需求、读取资料，再制作、检查、修正与交付。'],
   ['项目设计规范','_ds_prompt.md / _d_meta.json','恢复绑定的品牌、字体、组件与变量，继续任务时沿用已有依据。'],
   ['目标专项规则','built-in-skills/','手机关注触控与状态，PPT 关注画布和翻页，邮件遵守客户端兼容规则。'],
   ['实际代码与模板','starter-components/ / agents/','能共享的组件和变量直接复用；模板与脚本落实行为、结构和格式转换。'],
   ['检查与反馈','浏览器 / 专项检查器','检查运行结果、布局与对应结构，根据真实问题继续修改。']
  ].map(([title,file,desc])=><li key={title}><div><h4>{title}</h4><code>{file}</code></div><p>{desc}</p></li>)}</ol><div className="u-grid three"><article><span className="u-tag">同一个品牌 / 手机原型</span><h4>触控与交互状态</h4><p>品牌色和字体保持一致，另外处理触控目标、表单校验、页面切换和移动布局。</p></article><article><span className="u-tag">同一个品牌 / 产品 PPT</span><h4>画布与演示节奏</h4><p>沿用视觉规范，另外处理固定比例、文字尺寸、缩放、翻页和动画导出。</p></article><article><span className="u-tag">同一个品牌 / 营销邮件</span><h4>邮件客户端兼容</h4><p>沿用品牌表达，按邮件支持的布局实现；不能直接照搬普通网页的 React 组件。</p></article></div><div className="u-callout"><strong>文字要求、代码机制、检查证据，是三种不同的约束。</strong><p>“使用品牌紫色”是要求；引用同一个颜色变量是实现；运行页面再检查是证据。库没有自动解决全部冲突的强制规则引擎，AI 的遵循程度和实际执行仍需验证，用户要求与宿主更高优先级指令继续适用。</p></div></section>
  <section id="u-catalog" className="u-section"><div className="eyebrow">05 / SKILL CATALOG</div><h3>53 份说明，按工作职责理解。</h3><p>以下 8 组是我们的阅读归纳；文件来自固定版本。部分是协议、兼容入口和工具说明，不能当作 53 个独立功能。展开查看名称、作用和上游原文。</p><div className="u-catalog">{UNDERSTANDING.groups.map(group=><details key={group.title}><summary>{group.title}<span>{group.items.length} 份</span></summary><p>{group.description}</p><ul>{group.items.map(([name,desc])=><li key={name}><a href={upstream+'built-in-skills/'+name+'.md'} target="_blank" rel="noreferrer">{name}</a><span>{desc}</span></li>)}</ul></details>)}</div></section>
  <section id="u-rules" className="u-section"><div className="eyebrow">06 / RULES AND EVIDENCE</div><h3>覆盖广，靠的是复用方法、模板和浏览器。</h3><p>网页、幻灯片和可打印文档可以共享 HTML / CSS 的表达方式；动画、3D 和转换器在此基础上增加专用代码。能力入口覆盖广，不代表每条路径都同样成熟。</p><div className="u-rule-grid">{UNDERSTANDING.constraints.map(([title,desc])=><article key={title}><h4>{title}</h4><p>{desc}</p></article>)}</div><div className="u-grid three"><article><h4>文字约束</h4><p>要求 AI 遵守品牌、先看资料、完成后检查。是否遵循取决于宿主指令、模型、上下文和实际执行。</p></article><article><h4>代码机制</h4><p>共享组件和 CSS 变量直接影响页面；脚本执行编译、复制、格式转换，并检查其覆盖的结构规则。</p></article><article><h4>运行证据</h4><p>浏览器实际操作可以发现运行问题。工具检查通过，不能自动证明页面好看、用户体验优秀或已达到上线要求。</p></article></div><div className="boundary-grid"><div><h4>本次已实测</h4><ul><li>三种布局与搜索、收藏、阅读、添加、本地保存</li><li>设计系统编译、检查、导入、单文件预览</li><li>原版幻灯片舞台与可编辑 PPTX 导出</li><li>PPTX 的 4 页、可编辑对象与 3 组点击动画结构</li></ul></div><div><h4>仍是源码了解，尚未验证</h4><ul><li>真实 Figma 导入、Figma / Canva 交接</li><li>图片和音效生成、视频导出、3D 等专项路径</li><li>桌面 PowerPoint 中的字体和动画表现</li><li>与无 Skill 条件相比的审美、效率提升</li></ul></div></div><p className="u-note">前端原型不等于完整业务系统。账户、数据库、支付、安全与运维仍需实际开发和验证；本页没有连接在线模型或这些服务。</p></section>
  <section className="u-section"><h3>对我们更值得借鉴的三件事</h3><div className="u-grid three"><article><h4>按任务加载</h4><p>把入口写短，明确什么时候读哪份专项说明，避免每项任务都加载全部规则。</p></article><article><h4>规范绑定项目</h4><p>保存真实组件和品牌约束，继续任务时恢复；比每次重复泛泛的“做得好看”更可执行。</p></article><article><h4>用工具完成重复工作</h4><p>将编译、格式转换和结构检查交给脚本，把设计判断和反馈留给人及 AI；效果用实际结果评估。</p></article></div></section>
  <p className="source-line">固定版本 <a href={upstream} target="_blank" rel="noreferrer">026d4ea</a> · <a href="../notes/research.md" target="_blank">实测研究记录</a> · <a href="../notes/understanding.md" target="_blank">完整理解与比较</a> · <a href="../THIRD_PARTY_NOTICES.md" target="_blank">引用与许可</a> · 原创研究展厅 · 浏览本页不运行 AI</p>
 </section>;
}
