(() => {
  'use strict';
  const tools = [
    {id:'ua',name:'Understand Anything',role:'理解项目与引导阅读',group:'从材料提取关系',input:'代码仓库；约定的 Markdown Wiki；Figma 文件；已有图谱 JSON。',process:'程序扫描与结构解析，宿主模型补充职责、业务含义、分层与导览，再校验合并成图谱。',model:'完整语义分析需要宿主模型；结构解析和已有图谱浏览可独立进行。',output:'四类图谱内容：代码、业务领域、Wiki、设计；提供源码详情、导览、变更高亮及 JSON / PNG / SVG。',best:'接手陌生仓库、按阅读路线理解模块、把代码转成便于人的解释。',boundary:'业务归纳需核对。当前核心影响分析实测为一跳，结构指纹可能跳过函数体变化；不能替代运行时调试。',difference:'把提取、解释与阅读体验放在一条流程里。与 Graphify 的提取建图能力重合；图种广度不是它的主要优势。',example:'订单、库存、支付组成可探索地图；沿导览看职责、进入源码，再核对下单流程。',verified:'本次：6 个文件、12 节点 / 14 边的核心实验；原版浏览 / 导览。领域、Wiki、设计只验证人工 JSON 的原版渲染。',unverified:'完整 LLM 自动分析、真实 Figma API、自动业务归纳质量尚未验证。',version:'研究提交 6df3065',commit:'6df3065f1d8ddc2ce3615314d1d493f36d6b1c80',repo:'https://github.com/Egonex-AI/Understand-Anything',research:'#gallery',record:'../notes/research.md',license:'MIT'},
    {id:'graphify',name:'Graphify',role:'提取关系与查询图谱',group:'从材料提取关系',input:'源码、SQL、配置、文档及支持的 PDF、图片、音视频等；部分格式需可选组件。',process:'代码用 Tree-sitter / AST；语义资料由模型提取；去重建图后做社区、路径和邻域分析。',model:'代码结构可本地解析。本次 FastAPI 实验模型用量为 0；资料的语义提取需要模型。',output:'交互网络、层级树、调用流程、报告 / Wiki；JSON、GraphML、Cypher、Canvas；CLI / MCP 查询。',best:'查询依赖与路径、关联资料和来源、为 Agent 提供相关子图与可复用上下文。',boundary:'静态关系并非运行轨迹；提取与推断应分开。多模态支持不代表我们已逐项跑通。',difference:'与 Understand Anything 最接近。其已研究能力更侧重图分析、查询、来源区分和数据复用；UA 更侧重摘要、分层和阅读导览。',example:'查询 createOrder 与支付模块如何连接、谁调用库存检查，并导出关系或交给 Agent 查询。',verified:'历史实测：FastAPI 核心包 48 文件，747 节点 / 1,971 关系；原生网络 / 树 / 调用流程、查询、MCP 与增量样例已验证。',unverified:'文档 / 图片 / 音视频语义提取、数据库连接、跨项目全局图及长期 Agent 收益未实测。',version:'v0.9.57 · 3f82bf7',commit:'3f82bf7f837a07fb0f7668fbdbd5662801906942',repo:'https://github.com/Graphify-Labs/graphify',research:'https://yydshly.github.io/0911_codex_project/009-graphify/',record:'https://github.com/yydshly/0911_codex_project/blob/main/projects/009-graphify/README.md',license:'Apache-2.0；历史 MIT 与 NOTICE 见原研究'},
    {id:'archify',name:'Archify',role:'交互式系统设计交付',group:'把确认后的内容制成图',input:'用户或外部 Agent 编写的、有类型约束的 JSON 图规格；可附固定提交的源码引用。',process:'校验规格，执行专用布局与渲染，再检查和交付独立 HTML；可比较前后两个架构模型。',model:'AI 可读资料并编写规格；已有合规 JSON 后，渲染不必再次调用模型。',output:'架构、工作流、时序、数据流、生命周期五类图，以及架构模型差异；支持路径追踪和图片等导出。',best:'系统设计评审、交接讲解、请求往返解释、重构前后方案沟通。',boundary:'不内置通用代码关系提取。差异比较需要两个已有模型，不会独立把 Git diff 自动理解为架构变化。',difference:'UA 从材料建立理解；Archify 将已经整理好的系统知识交付成专门的技术图。它可画时序图，但关系事实须先准备。',example:'作者确认下单过程后，编写订单 API、库存、支付的 JSON，生成请求时序图及架构差异。',verified:'历史实测：五类原生图与模型差异、中文源码案例、来源校验、交互路径、多格式导出及预览恢复。',unverified:'输入规格由 Agent 阅读后编写；没有验证“库独立扫描源码到出图”。个别导出交互问题记录在原研究。',version:'2.17.0-dev.1 · 1072200',commit:'10722002bb8777ecb639d93c49586fae4adf3ae4',repo:'https://github.com/tt-a1i/archify',research:'https://yydshly.github.io/0909_codex_project/projects/003-archify/',record:'https://github.com/yydshly/0909_codex_project/blob/main/projects/003-archify/README.md',license:'MIT；字体等另见原研究声明'},
    {id:'diagram',name:'Diagram Design',role:'面向读者的说明与配图',group:'把确认后的内容制成图',input:'文字、整理后的数据与关系，或 Mermaid / draw.io / Excalidraw 图源文件。',process:'Skill 指导选图、信息取舍、品牌与布局；AI 编写 HTML / SVG，辅助脚本解析旧图并检查产物。',model:'生成与重绘主要由 AI 按规范执行；SVG 的布局设计不是完全交给通用自动布局程序。',output:'研究版本列出 40 种基础图型；HTML / SVG / PNG，品牌风格、解释页面及可选分步动画。',best:'文章配图、项目介绍、教学讲解、汇报图解、旧图换风格与简化重绘。',boundary:'效果依赖模型执行与复核；大图可能需拆分。40 种图型规范不等于 40 个独立渲染引擎。',difference:'UA 帮人探索已有项目；Diagram Design 帮作者挑选信息并表达给读者，关注字体、密度、品牌与叙述方式。',example:'把已核实的下单逻辑，提炼成三阶段说明图或一张适合文章、幻灯片使用的配图。',verified:'历史研究：57 组 / 155 个上游 HTML；8 个中文案例导出；三种旧图导入实验及相关检查。',unverified:'中文图由 AI 按规范编写；并非自动提取仓库事实。复杂项目的整体生成质量没有统一基准测试。',version:'2.6.23 · ce9344c',commit:'ce9344c52cb9be811de187bf2a6d58c712c9c9fe',repo:'https://github.com/cathrynlavery/diagram-design',research:'https://yydshly.github.io/0914_codex_project/005-diagram-design/',record:'https://github.com/yydshly/0914_codex_project/blob/main/projects/005-diagram-design/README.md',license:'MIT；图标等另见原研究声明'},
    {id:'fireworks',name:'Fireworks',role:'工程技术图绘制与检查',group:'把确认后的内容制成图',input:'符合约定的图纸 JSON，或 AI 按图型规范编写的 SVG；位置、结构、领域字段需要准备。',process:'JSON 路线绘制节点并路由连线；另一条路线检查 AI 编写 SVG；检查几何、文字与部分工程领域约束，再导出。',model:'可由外部模型整理内容与图纸；已有合规输入时不强制调用模型。自动路由不等于全部自动布局。',output:'系统 / C4 / 部署 / 数据 / UML 与 AI 工作流等表达；SVG / PNG / 离线 HTML，受支持场景可导出 GIF。',best:'工程文档、技术方案、Agent / RAG 说明、需要检查连线和文字的统一风格配图。',boundary:'不自动验证业务事实。部分图型由 AI 写 SVG；不能把所有条目都称作专用渲染器或完整 UML 标准实现。',difference:'UA 关注结构与解释；Fireworks 关注图纸的工程表达、样式、连线路由和产物检查。图纸质量仍依赖输入。',example:'把确认后的订单服务、数据库、事件总线画成技术架构图，检查重叠、截字与箭头并导出。',verified:'历史展厅：33 个图型 / 领域条目，其中 15 项原生 JSON、18 项 AI 编写 SVG 后导出，后者含 3 项近似适配。',unverified:'GIF 使用上游发布样片，本次历史研究未重新编码；不存在跨图型全自动代码分析验证。',version:'包版本 1.2.0 · 31fea36',commit:'31fea364eda5f1852b1175f3d9e29ea31d22dcb4',repo:'https://github.com/yizhiyanhua-ai/fireworks-tech-graph',research:'https://yydshly.github.io/0915_codex_project/003-fireworks-tech-graph/',record:'https://github.com/yydshly/0915_codex_project/blob/main/projects/003-fireworks-tech-graph/README.md',license:'MIT'},
  ];
  const cases = [
    {title:'我想先看懂一个仓库',tool:'ua',why:'从模块全貌、通俗说明和阅读路线入手，再点进源码。',prepare:'本地代码仓库与可运行技能的 AI 环境；先选一个模块试验。',deliver:'带分层、摘要与阅读导览的可浏览图谱。',alternative:'如果核心问题是“两个符号怎样关联、谁依赖谁”，转向 Graphify 的路径与查询能力。',check:'抽样核对文件位置、遗漏关系与摘要；完整自动生成质量仍需验证。'},
    {title:'我想查询依赖、连接资料',tool:'graphify',why:'先建立可查询关系图，再用邻域、路径、来源标签和 CLI / MCP 复用结果。',prepare:'目标源码或支持的资料；语义资料需模型及相应依赖。',deliver:'可查询的图谱数据、相关子图、报告或 Wiki。',alternative:'需要面向新人的分层解释和阅读导览时，也可试 Understand Anything；先用同一小样本比较。',check:'区分提取与推断；大规模与多模态收益不能从 FastAPI 样本直接推断。'},
    {title:'我要做设计评审或交接',tool:'archify',why:'用架构、时序、数据流等不同视角讲解，并支持节点、路径与前后模型比较。',prepare:'已核实的组件、消息或数据流；需要时准备前后两个 JSON 模型。',deliver:'独立可交互 HTML 与可导出的技术图。',alternative:'如果还没弄清代码关系，先用 UA / Graphify 或人工分析；如果只需一张简洁配图，可用 Diagram Design。',check:'确定箭头含义和时序来源；模型差异不等于运行时变化的全部影响。'},
    {title:'我要写文章、汇报或教学',tool:'diagram',why:'把确认后的内容按读者需要做取舍，统一字体、品牌与信息密度。',prepare:'核心结论、目标读者、使用尺寸与已确认的关系。',deliver:'HTML 说明页面、SVG 或 PNG 配图。',alternative:'需要交互追踪系统路径可用 Archify；需要工程字段和几何检查可用 Fireworks。',check:'检查文字、连线与信息删减；抽象后的图不应被当作完整源码拓扑。'},
    {title:'我要画工程或 AI 系统图',tool:'fireworks',why:'适合架构、部署、Agent / RAG 等表达，可配合连线路由与文字、几何检查。',prepare:'已整理的节点、关系、必要坐标与领域字段，选择合适的图型路线。',deliver:'SVG、PNG 或离线 HTML；动画需满足支持的语义场景。',alternative:'重点是时序讲解和设计模型差异时看 Archify；重点是文章表达与重绘看 Diagram Design。',check:'先确认该图型走原生 JSON 还是 AI SVG；检查通过也不证明业务正确。'},
    {title:'我要把已有图重新设计',tool:'diagram',why:'已有 Mermaid / draw.io / Excalidraw 可先提取结构，再按新的读者、尺寸与风格重绘。',prepare:'可读取的图源文件、必须保留的事实、目标风格。',deliver:'新的 HTML / SVG / PNG，必要时附结构删改说明。',alternative:'如果已经有符合 Archify 或 Fireworks 的 JSON 规格，可以直接用对应渲染器，不必重复理解全部资料。',check:'导入支持范围有限；重绘会改变布局与样式，需要检查节点与关系是否丢失。'},
    {title:'我要检查设计系统的关系',tool:'ua',why:'已有 understand-figma 入口可提取页面、组件、实例与 token 的关系，并复用结构视图。',prepare:'已有 Figma 文件 URL / key、合法访问权限与 token。',deliver:'已有设计对象的知识图谱，而非新 UI 或可发布的设计稿。',alternative:'如果目标是生成新界面或把代码还原成设计，需要另选设计工具；这里五个工具的已验证范围不足以覆盖。',check:'本次只用人工设计 JSON 验证原版渲染，真实 API 与自动设计分析尚未验证。'},
  ];
  const $=id=>document.getElementById(id);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const external=(url,label)=>`<a href="${url}" ${url.startsWith('http')?'target="_blank" rel="noreferrer"':''}>${label} ↗</a>`;
  function showTool(id){
    const t=tools.find(t=>t.id===id);
    for(const b of $('compare-tools').querySelectorAll('button')) b.setAttribute('aria-pressed',String(b.dataset.compareTool===id));
    $('compare-detail').innerHTML=`<div class="compare-detail-head"><div><span class="eyebrow">${t.group}</span><h2>${t.name}</h2><p>${t.role}</p></div><span class="compare-version">${t.version}</span></div><p class="compare-difference">${t.difference}</p><div class="compare-detail-fields">${[['输入来源',t.input],['处理原理',t.process],['大模型与人的分工',t.model],['产物与效果',t.output],['适合的场景',t.best],['能力边界',t.boundary]].map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div><div class="compare-proof"><div><h3>已有研究实测</h3><p>${t.verified}</p></div><div><h3>仍未验证的部分</h3><p>${t.unverified}</p></div></div><div class="compare-links">${external(t.research,'研究展厅')}${external(t.repo+'/tree/'+t.commit,'固定版本源码')}${external(t.record,'研究记录')}<span>${t.license}</span></div>`;
  }
  $('compare-tools').innerHTML=tools.map((t,i)=>`<button data-compare-tool="${t.id}" aria-pressed="${i===0}"><span>0${i+1}</span><strong>${t.name}</strong><small>${t.role}</small></button>`).join('');
  for(const b of $('compare-tools').querySelectorAll('button')) b.addEventListener('click',()=>showTool(b.dataset.compareTool));
  function showCase(i){const c=cases[i],t=tools.find(t=>t.id===c.tool);for(const b of $('compare-cases').querySelectorAll('button'))b.setAttribute('aria-pressed',Number(b.dataset.compareCase)===i?'true':'false');$('compare-recommendation').innerHTML=`<span class="eyebrow">适用性建议 · 依据既有研究</span><h2>${c.title}</h2><div class="compare-recommend"><span>优先尝试</span><strong>${t.name}</strong></div><p>${c.why}</p><dl><dt>先准备</dt><dd>${c.prepare}</dd><dt>得到什么</dt><dd>${c.deliver}</dd><dt>何时换用其他工具</dt><dd>${c.alternative}</dd><dt>怎样确认有效</dt><dd>${c.check}</dd></dl><button class="compare-open" data-open-tool="${t.id}">查看 ${t.name} 的能力与证据 ↓</button>`;$('compare-recommendation').querySelector('button').addEventListener('click',()=>{showTool(t.id);$('compare-detail').scrollIntoView({behavior:'smooth',block:'start'});$('compare-detail').focus({preventScroll:true});});}
  $('compare-cases').innerHTML=cases.map((c,i)=>`<button data-compare-case="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${c.title}<b>↗</b></button>`).join('');
  for(const b of $('compare-cases').querySelectorAll('button'))b.addEventListener('click',()=>showCase(Number(b.dataset.compareCase)));
  $('compare-matrix').innerHTML=tools.map(t=>`<tr><th scope="row">${t.name}<small>${t.role}</small></th><td>${t.id==='ua'?'程序提取 + 模型语义归纳':t.id==='graphify'?'本地代码解析 + 资料语义提取':'用户 / 外部 Agent 准备事实'}</td><td>${t.id==='ua'?'分层、摘要、源码与阅读导览':t.id==='graphify'?'图查询、路径、社区、来源与数据导出':t.id==='archify'?'五类技术图、交互路径、前后模型差异':t.id==='diagram'?'选图、信息取舍、品牌布局、旧图重绘':'工程图纸、路由、几何检查与导出'}</td><td>${t.best}</td><td>${external(t.research,'看历史成果')}</td></tr>`).join('');
  $('compare-example').innerHTML=tools.map(t=>`<article><span>${t.name}</span><p>${t.example}</p></article>`).join('');
  showTool('ua');showCase(0);
})();
