(() => {
  'use strict';
  const root = 'https://github.com/Egonex-AI/Understand-Anything/blob/6df3065f1d8ddc2ce3615314d1d493f36d6b1c80/understand-anything-plugin/';
  const categories = { all:'全部效果', code:'代码与架构', domain:'业务领域', knowledge:'Wiki 知识', design:'Figma 设计', helper:'辅助效果' };
  // All small diagrams are authored explanations. They do not copy the native UI.
  const n = (name, desc, x, y) => ({name,desc,x,y});
  const entries = [
    {id:'architecture',cat:'code',title:'架构分层图',subtitle:'先看全貌，再进入模块',question:'这个项目由哪几层组成？',effect:'将多个文件归入架构层，以层级卡片展示；进入某一层后继续展开文件与符号。',input:'本地代码仓库；分层与摘要由分析流程生成。',command:'/understand --language zh',source:'skills/understand/SKILL.md',boundary:'层级是归纳结果，需要核对；并非完整 C4 或部署图规范。',proof:'解析样本 + 人工分层 · 原版实测',shot:'upstream-overview.png',caption:'原版 Dashboard 实际加载 Order Lab。结构经上游解析；中文摘要、层级和导览为研究者编写。',nodes:[n('入口层','接收结账请求',60,70),n('业务层','协调订单、库存',340,70),n('基础设施层','支付与持久化',620,70),n('数据层','SQL 表结构样本',620,260)],edges:[[0,1,'层间依赖'],[1,2,'层间依赖']],note:'此示意按样本分层简化；SQL 样本没有已解析的读写连线。'},
    {id:'dependencies',cat:'code',title:'文件与模块依赖图',subtitle:'谁导入了谁',question:'一个模块依赖哪些文件？',effect:'以文件为节点、imports / exports / depends_on 为关系，按依赖方向浏览相邻模块。',input:'源码及可解析的导入语句。',command:'/understand --language zh',source:'packages/core/src/types.ts',boundary:'语言和动态导入会影响提取覆盖；箭头不代表执行先后。',proof:'imports 样本已实测 · 独立示意',nodes:[n('api.ts','请求入口',50,165),n('orders.ts','订单协调',330,165),n('inventory.ts','库存规则',610,35),n('payment.ts','支付服务',610,165),n('repository.ts','数据访问',610,295)],edges:[[0,1,'imports'],[1,2,'imports'],[1,3,'imports'],[1,4,'imports']],note:'四条 imports 对应已解析订单样本。',action:true},
    {id:'calls',cat:'code',title:'函数调用关系图',subtitle:'从入口追到具体实现',question:'结账入口调用了哪些函数？',effect:'将函数作为节点，沿 calls 关系查找调用者与被调用者；点击查看路径、行号和源码。',input:'函数定义、调用语法与可解析的符号关系。',command:'/understand --language zh',source:'packages/core/src/plugins/tree-sitter-plugin.ts',boundary:'是静态关系；不代表真实运行轨迹、请求耗时或完整时序图。',proof:'calls 样本已实测 · 独立示意',nodes:[n('handleCheckout','结账请求',50,165),n('createOrder','协调下单',330,165),n('reserveStock','预留库存',610,35),n('chargePayment','发起支付',610,165),n('saveOrder','保存结果',610,295)],edges:[[0,1,'calls'],[1,2,'calls'],[1,3,'calls'],[1,4,'calls']],note:'四条调用关系来自样本解析与直接导入适配；分支不表达执行顺序。',action:true},
    {id:'types',cat:'code',title:'类与接口关系图',subtitle:'继承、实现、包含',question:'某个类继承谁、实现什么接口？',effect:'类、模块与文件使用同一结构图谱，通过 inherits、implements、contains 表达类型关系。',input:'支持语言中的类定义、继承和接口信息。',command:'/understand --language zh',source:'packages/core/src/types.ts',boundary:'关系模型支持这些边；不是带全部成员分栏、可见性等记法的标准 UML 类图。本样本未验证自动抽取。',proof:'源码定义已核对 · 人工关系示意',nodes:[n('OrderService','订单实现类',340,165),n('BaseService','基类',620,65),n('IOrderService','接口',620,265),n('services.ts','类所在文件',60,165)],edges:[[0,1,'inherits'],[0,2,'implements'],[3,0,'contains']],note:'原创示例，未从真实工程抽取。'},
    {id:'data',cat:'code',title:'数据读写与结构关系图',subtitle:'服务、表、模式与校验',question:'哪个服务读写哪张表？',effect:'以 service、table、schema 等为节点，表达 reads_from、writes_to、validates、transforms 等关系。',input:'源码、SQL、模式与配置；部分关联需要语义分析。',command:'/understand --language zh',source:'packages/core/src/types.ts',boundary:'SQL 表解析已实测；这里的读写连线为人工示例。没有独立的标准 ER 基数图生成器。',proof:'表结构已实测 · 读写为人工示意',nodes:[n('订单服务','业务逻辑',340,165),n('products 表','读取商品',620,65),n('orders 表','写入订单',620,265),n('订单 Schema','校验输入',60,165)],edges:[[0,1,'reads_from'],[0,2,'writes_to'],[3,0,'validates']],note:'不要将关系类型可用误认为所有表的读写关系均可自动识别。'},
    {id:'infra',cat:'code',title:'服务与基础设施关系图',subtitle:'部署、触发与资源依赖',question:'服务、配置和部署资源怎样关联？',effect:'service、resource、pipeline、config 等节点连接为统一图谱，表达部署、配置与触发关系。',input:'部署清单、流水线文件、配置及关联源码。',command:'/understand --language zh',source:'packages/core/src/types.ts',boundary:'不是云资源实时探测或监控拓扑。基础设施提取覆盖取决于解析器与模型。',proof:'源码定义已核对 · 人工关系示意',nodes:[n('CI 流水线','部署入口',60,165),n('API 服务','运行应用',340,165),n('配置文件','提供配置',340,35),n('数据库资源','存储依赖',620,165)],edges:[[0,1,'deploys'],[2,1,'configures'],[1,3,'depends_on']],note:'原创说明样本，不代表已连接真实云环境。'},
    {id:'domains',cat:'domain',title:'业务领域总览图',subtitle:'跨领域协作，一眼看到',question:'订单、库存、支付如何协作？',effect:'横向展示领域卡片，包含实体、摘要、流程数量；虚线表示跨领域联系，双击领域进入流程。',input:'已有代码图谱；或轻量扫描代码仓库。',command:'/understand-domain',source:'skills/understand-domain/SKILL.md',boundary:'业务划分和规则来自归纳，不代表已验证的业务事实。',proof:'人工样本 · 原版渲染已验证',shot:'gallery-domain.png',fixture:'domain',caption:'原版领域视图，加载研究者编写的 8 节点 / 7 边样本；未运行自动业务提取。',nodes:[n('订单领域','订单、购物车',60,165),n('库存领域','商品、库存',620,65),n('支付领域','支付单',620,265)],edges:[[0,1,'cross_domain'],[0,2,'cross_domain']],note:'横向领域布局；人工示例。'},
    {id:'steps',cat:'domain',title:'业务流程与步骤图',subtitle:'从领域深入到做事步骤',question:'提交订单具体包含哪些步骤？',effect:'进入领域后，展示业务流程与步骤节点，附入口类型与源码线索。原版将流程连接到各步骤，步骤编号辅助阅读。',input:'领域图谱中的 flow、step 与 flow_step 关系。',command:'/understand-domain',source:'packages/dashboard/src/components/DomainGraphView.tsx',boundary:'原版是“流程 → 步骤”的关系展开；不等于完整 BPMN，也不凭连线证明执行时序。',proof:'人工样本 · 原版展开已验证',shot:'gallery-domain-detail.png',fixture:'domain',caption:'双击订单领域后的原版界面：一个流程、四个步骤。数据由研究者编写，未验证 LLM 流程推断。',nodes:[n('提交订单','HTTP 入口',60,165),n('01 校验商品','商品与数量',365,40),n('02 预留库存','库存规则',650,40),n('03 发起支付','请求收款',365,280),n('04 保存订单','记录状态',650,280)],edges:[[0,1,'flow_step'],[0,2,'flow_step'],[0,3,'flow_step'],[0,4,'flow_step']],note:'关系示意保留流程到步骤的连接方式；不会伪造步骤间的运行时调用。'},
    {id:'wiki',cat:'knowledge',title:'Wiki 知识关系图',subtitle:'主题、文章、观点与来源',question:'哪些观点有关联、引用了什么？',effect:'力导向网络布局；节点按主题社区组织，引用、矛盾、举例等关系用不同线条呈现。',input:'符合约定的 Markdown Wiki、wikilinks、原始来源与说明文件。',command:'/understand-knowledge ./wiki',source:'skills/understand-knowledge/SKILL.md',boundary:'不是任意网页自动抓取器。语义关系需要模型，观点矛盾也需要结合上下文确认。',proof:'人工样本 · 原版渲染已验证',shot:'gallery-knowledge.png',fixture:'knowledge',caption:'原版知识视图渲染 6 节点 / 6 边的人工 Wiki 样本；“缓存”观点仅用于演示关系，不是真实研究结论。',nodes:[n('缓存实践笔记','文章',340,165),n('缓存策略','主题',60,45),n('实验记录 A','来源',60,285),n('降低延迟','观点',620,45),n('可能增加延迟','相反观点',620,285)],edges:[[0,1,'categorized_under'],[0,2,'cites'],[0,3,'builds_on'],[4,3,'contradicts']],note:'原创说明图；原版使用力导向布局，节点位置不同。'},
    {id:'figma',cat:'design',title:'Figma 设计知识图',subtitle:'页面、组件、实例与变量',question:'界面使用哪些组件和设计变量？',effect:'将 Figma 对象变成节点，显示组件实例、变体和 token 引用。当前复用结构图谱界面，可展开到具体设计节点。',input:'已有 Figma 文件 URL / key，以及 FIGMA_TOKEN。',command:'/understand-figma <Figma 文件 URL>',source:'skills/understand-figma/SKILL.md',boundary:'分析已有设计关系，不生成新界面。本次未连接 Figma API；原型跳转关系仍不是已实现的独立流程视图。',proof:'人工样本 · 原版渲染已验证',shot:'gallery-design.png',fixture:'design',caption:'原版结构视图渲染人工设计样本。6 类节点均有定义；本次没有抓取真实 Figma 文件或生成 UI。',nodes:[n('结账界面','screen',60,165),n('提交按钮实例','instance',340,165),n('Primary 按钮','component',620,165),n('Button 组件集','componentSet',620,35),n('品牌主色','token',620,295)],edges:[[0,1,'contains'],[1,2,'instance_of'],[2,3,'variant_of'],[2,4,'uses_token']],note:'复用结构图谱；设计样本的页面节点可在原始 JSON 中查看。'},
    {id:'impact',cat:'helper',title:'变更影响高亮',subtitle:'在已有图上看改动',question:'改支付代码，会牵涉哪些直接邻居？',effect:'把变更文件映射到图节点，突出修改位置及直接连接节点。可配合图谱继续阅读。',input:'已有图谱与 Git 差异。',command:'/understand-diff',source:'src/diff-analyzer.ts',boundary:'属于已有图的叠加效果，不是新图种。核心实验覆盖一跳，不能当作完整间接影响或运行时风险。',proof:'核心分析已实测 · 独立高亮示意',nodes:[n('handleCheckout','间接关系：不在一跳结果',60,165),n('createOrder','直接关联',340,165),n('chargePayment','修改位置',620,165)],edges:[[0,1,'calls'],[1,2,'calls']],note:'在“动手探索”选择 payment.ts 可查看真实核心结果。',action:true},
    {id:'tour',cat:'helper',title:'按步骤阅读导览',subtitle:'让同一张图带你学习',question:'第一次阅读应该从哪里开始？',effect:'按预设路线聚焦节点，显示说明，逐步阅读入口、业务和基础设施。',input:'图谱 JSON 中的 tour 步骤。',command:'/understand-dashboard',source:'packages/core/src/types.ts',boundary:'导览是一种阅读方式，不是新的图种。本样本导览由研究者编写。',proof:'人工导览 · 原版交互已验证',shot:'upstream-tour.png',caption:'原版阅读导览真实截图；数据与路线来自本研究样本。',nodes:[n('01 入口','进入请求',60,165),n('02 订单','理解协调',340,165),n('03 库存','继续阅读',620,165)],edges:[[0,1,'阅读路线'],[1,2,'阅读路线']],note:'箭头表示研究者安排的阅读顺序，不代表新的源码关系。'},
  ];
  const families = [
    ['结构关系','imports · exports · contains · inherits · implements'],
    ['行为关系','calls · subscribes · publishes · middleware'],
    ['数据流关系','reads_from · writes_to · transforms · validates'],
    ['依赖关系','depends_on · tested_by · configures'],
    ['语义关系','related · similar_to'],
    ['基础设施与模式','deploys · serves · provisions · triggers · migrates · documents · routes · defines_schema'],
    ['业务领域关系','contains_flow · flow_step · cross_domain'],
    ['知识关系','cites · contradicts · builds_on · exemplifies · categorized_under · authored_by'],
    ['设计关系','instance_of · variant_of · uses_token'],
  ];
  const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let category = 'all', selected = entries[0], mode = 'native';
  function drawing(entry, interactive=false) {
    const prefix = `arrow-${entry.id}-${interactive?'large':'small'}`;
    return `<svg viewBox="0 0 900 410" ${interactive?'role="group"':'role="img"'} aria-label="${entry.title}：研究者关系示意"><defs><marker id="${prefix}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>${entry.edges.map(([a,b,label])=>{const s=entry.nodes[a],t=entry.nodes[b];const dx=t.x-s.x,dy=t.y-s.y;const horizontal=Math.abs(dx)>=Math.abs(dy);const x1=s.x+100+(horizontal?Math.sign(dx)*100:0),y1=s.y+30+(horizontal?0:Math.sign(dy)*30),x2=t.x+100-(horizontal?Math.sign(dx)*100:0),y2=t.y+30-(horizontal?0:Math.sign(dy)*30);return `<path class="sample-edge" d="M${x1},${y1} L${x2},${y2}" marker-end="url(#${prefix})"/><text class="sample-edge-label" x="${(x1+x2)/2}" y="${(y1+y2)/2-9}" text-anchor="middle">${esc(label)}</text>`;}).join('')}${entry.nodes.map((node,i)=>`<g ${interactive?`role="button" tabindex="0" aria-label="查看示意节点 ${esc(node.name)}" data-sample-node="${i}"`:''} class="sample-node ${entry.id==='impact'?(i===2?'changed':i===1?'affected':''):''}" transform="translate(${node.x},${node.y})"><rect width="200" height="60" rx="9"/><text x="16" y="26">${esc(node.name)}</text><text class="sample-node-desc" x="16" y="46">${esc(node.desc)}</text></g>`).join('')}</svg>`;
  }
  const $ = id => document.getElementById(id);
  function detail() {
    $('gallery-focus').dataset.category = selected.cat;
    $('gallery-focus').innerHTML = `<div class="gallery-detail-head"><div><span class="eyebrow">${categories[selected.cat]} / ${String(entries.indexOf(selected)+1).padStart(2,'0')}</span><h2>${selected.title}</h2><p>${selected.question}</p></div><span class="gallery-proof">${selected.proof}</span></div><div class="gallery-detail-grid"><div class="gallery-preview"><div class="gallery-view-switch"><button data-gallery-mode="native" ${!selected.shot?'disabled':''} aria-pressed="${mode==='native'}">原版运行截图</button><button data-gallery-mode="diagram" aria-pressed="${mode==='diagram'}">关系示意 · 可点击</button>${selected.shot?`<a href="../assets/${selected.shot}" target="_blank" rel="noreferrer">查看原图 ↗</a>`:''}</div>${mode==='native'?`<a href="../assets/${selected.shot}" target="_blank" rel="noreferrer"><img class="gallery-native" src="../assets/${selected.shot}" width="1500" height="960" alt="${selected.title}：${esc(selected.caption)}"></a><p class="gallery-caption">${selected.caption}</p>`:`<div class="gallery-diagram">${drawing(selected,true)}</div><p class="gallery-caption">研究者绘制的关系说明，非原版截图。${selected.note}</p><div id="sample-node-info" class="sample-node-info" aria-live="polite">点击图中节点，查看它与其他对象的关系。</div>`}</div><article class="gallery-explanation"><h3>呈现效果</h3><p>${selected.effect}</p><h3>需要什么输入</h3><p>${selected.input}</p><h3>怎样生成</h3><code>${esc(selected.command)}</code><small>以上为上游技能名写法；Codex 使用 $ 前缀。<a href="#guide">安装与运行指南 →</a></small><h3>能力边界</h3><p>${selected.boundary}</p><div class="gallery-links"><a href="${root+selected.source}" target="_blank" rel="noreferrer">固定版本源码 ↗</a>${selected.fixture?`<a href="../code/gallery-fixtures/${selected.fixture}.json" download>人工样本 JSON ↓</a>`:''}${selected.action?'<a href="#graph">探索实测样本 →</a>':''}</div></article></div>`;
    for(const button of $('gallery-focus').querySelectorAll('[data-gallery-mode]')) button.addEventListener('click',()=>{mode=button.dataset.galleryMode;detail();$('gallery-focus').querySelector(`[data-gallery-mode="${mode}"]`).focus({preventScroll:true});});
    for(const node of $('gallery-focus').querySelectorAll('[data-sample-node]')) {
      const activate=()=>{const i=Number(node.dataset.sampleNode);$('sample-node-info').textContent=selected.nodes[i].name+'：'+selected.nodes[i].desc+'。关联：'+(selected.edges.filter(([a,b])=>a===i||b===i).map(([a,b,label])=>`${selected.nodes[a].name} → ${label} → ${selected.nodes[b].name}`).join('；')||'无示例连线');};
      node.addEventListener('click',activate);node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}});
    }
  }
  function cards() {
    const visible=entries.filter(e=>category==='all'||e.cat===category);
    $('gallery-count').textContent=`${visible.length} 个展示条目 · ${category==='all'?'4 大类别 + 2 种辅助效果':categories[category]}`;
    $('gallery-cards').innerHTML=visible.map(e=>`<button class="gallery-card" data-gallery-entry="${e.id}" data-category="${e.cat}" aria-pressed="${e===selected}"><span class="gallery-card-top">${categories[e.cat]}<span>${e.shot?'含原版截图':'关系示意'}</span></span><div class="gallery-thumb">${drawing(e)}</div><strong>${e.title}</strong><span class="gallery-card-sub">${e.subtitle}<b>↗</b></span><small>${e.proof}</small></button>`).join('');
    for(const button of $('gallery-cards').querySelectorAll('button')) button.addEventListener('click',()=>{selected=entries.find(e=>e.id===button.dataset.galleryEntry);mode=selected.shot?'native':'diagram';cards();detail();$('gallery-focus').scrollIntoView({behavior:'smooth',block:'start'});$('gallery-focus').focus({preventScroll:true});});
  }
  $('gallery-filters').innerHTML=Object.entries(categories).map(([key,label])=>`<button data-gallery-filter="${key}" aria-pressed="${key==='all'}">${label}<span>${key==='all'?entries.length:entries.filter(e=>e.cat===key).length}</span></button>`).join('');
  for(const button of $('gallery-filters').querySelectorAll('button')) button.addEventListener('click',()=>{category=button.dataset.galleryFilter;for(const b of $('gallery-filters').querySelectorAll('button'))b.setAttribute('aria-pressed',String(b===button));if(category!=='all'&&selected.cat!==category){selected=entries.find(e=>e.cat===category);mode=selected.shot?'native':'diagram';}cards();detail();});
  $('relation-families').innerHTML=families.map(([name,types])=>`<tr><td>${name}</td><td>${types}</td></tr>`).join('');
  cards();detail();
})();
