import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath, pathToFileURL} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const url=process.argv[2]||'http://127.0.0.1:8770/projects/011-selfteaching/demo/';
const record=process.argv[3]||'browser.json';
assert.match(record,/^[a-z-]+\.json$/);
const capture=process.argv.includes('--screenshots');
const key='selfteaching-guide-011-v1';
const routes=JSON.parse(await readFile(path.join(root,'code/routes.json'),'utf8'));
const chapters=JSON.parse(await readFile(path.join(root,'code/chapters.json'),'utf8'));
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
const visible=()=>page.locator('.chapter:visible').count();
try{
 assert.equal((await page.goto(url)).status(),200);
 assert.equal(await page.locator('h1').count(),1);
 assert.equal(await page.locator('.chapter').count(),46);
 assert.equal(await page.locator('.lane').count(),3);
 assert.equal(await page.locator('.detail-grid article').count(),9);
 assert.equal(await page.locator('.project-card').count(),3);
 assert.equal(await page.locator('.obstacle-list details').count(),7);
 assert.equal(await page.locator('[data-check]').count(),8);
 assert.equal(await page.locator('.chapter a[href*="/blob/987a8e8a9ce205b63886510e145437d14d8a13a4/"]').count(),92);
 assert.match(await page.locator('#sources').textContent(),/未执行原书 Notebook/);
 assert.match(await page.locator('#chapter-40 a').first().getAttribute('href'),/Q.good-communiation.md/);
 assert.match(await page.locator('#chapter-40 a').nth(1).getAttribute('href'),/Q.good-communication.ipynb/);
 checks.push('46 章、92 个固定版本入口、三类九项能力、三个实践、七个卡点、八项自查及范围说明');
 for(const term of ['能力与方向','方法与技巧','提供哪些资料','对我的意义','刻意练习','Jupyter Notebook','AI'])assert.ok((await page.locator('#use-summary').textContent()).includes(term));
 checks.push('项目摘要覆盖能力方向、技巧、资料与个人使用意义');
 if(capture)await page.screenshot({path:path.join(root,'assets/cover.png')});
 for(const id of ['method','builder','reader','beginner']){
  await page.locator('[data-route="'+id+'"]').click();
  assert.equal(await page.locator('#route-title').textContent(),routes[id].name);
  assert.equal(await page.locator('#route-steps>li').count(),4);
  const count=routes[id].chapters==='all'?46:routes[id].chapters.length;
  assert.equal(await page.locator('.route-mark:visible').count(),count);
  await page.reload();
  assert.equal(await page.locator('[data-route="'+id+'"]').getAttribute('aria-pressed'),'true');
 }
 await page.goBack();
 assert.equal(await page.locator('[data-route="reader"]').getAttribute('aria-pressed'),'true');
 await page.goForward();
 assert.equal(await page.locator('[data-route="beginner"]').getAttribute('aria-pressed'),'true');
 await page.locator('[data-route="method"]').focus();await page.keyboard.press('Enter');
 assert.equal(await page.locator('[data-route="method"]').getAttribute('aria-pressed'),'true');
 checks.push('四条路线内容与阶段、章节高亮、URL、刷新、前进后退和键盘操作');
 if(capture){await page.locator('#path').screenshot({path:path.join(root,'assets/guide-detail.png')});}
 await page.locator('#route-filter').click();
 assert.equal(await visible(),routes.method.chapters.length);
 await page.locator('#category').selectOption('python');
 assert.equal(await visible(),0);
 assert.equal(await page.locator('#empty-state').isVisible(),true);
 await page.locator('#empty-clear').click();
 assert.equal(await visible(),46);
 await page.locator('#search').fill('函数');
 assert.ok((await visible())>5&&(await visible())<46);
 await page.locator('#category').selectOption('python');
 const expected=chapters.filter(c=>c.category==='python'&&[c.title,c.summary,c.task,c.label,c.part].join(' ').includes('函数')).length;
 assert.equal(await visible(),expected);
 await page.locator('#search').fill('zzzz<no-match>');
 assert.equal(await visible(),0);
 await page.locator('#clear-filters').click();
 checks.push('搜索、能力分类、路线组合筛选与空结果恢复');
 await page.locator('#search').fill('zzzz');
 await page.evaluate(()=>{location.hash='chapter-25'});
 await page.waitForFunction(()=>document.querySelector('#chapter-25 details').open);
 assert.equal(await visible(),46);
 assert.equal(await page.locator('#chapter-25 details').getAttribute('open'),'');
 await page.reload();
 assert.equal(await page.locator('#chapter-25 details').getAttribute('open'),'');
 await page.locator('[data-complete="25"]').check();
 assert.equal(await page.locator('#read-count').textContent(),'1');
 await page.locator('#only-unread').check();
 assert.equal(await visible(),45);
 await page.locator('#clear-filters').click();
 checks.push('章节深链自动展开、被筛选隐藏的目标恢复、已读与未读筛选');
 await page.locator('[data-check="reading"]').check();
 await page.locator('[data-check="testing"]').check();
 await page.locator('#learning-note').fill('目标：独立整理文本。\n证据：sample.txt\n下一步：检查空输入。<script>alert(1)</script>');
 await page.reload();
 assert.equal(await page.locator('[data-complete="25"]').isChecked(),true);
 assert.equal(await page.locator('[data-check="reading"]').isChecked(),true);
 assert.equal(await page.locator('#check-progress').getAttribute('value'),'2');
 assert.match(await page.locator('#learning-note').inputValue(),/<script>alert\(1\)<\/script>/);
 const downloadPromise=page.waitForEvent('download');
 await page.locator('#export-notes').click();
 const download=await downloadPromise;
 const exported=await readFile(await download.path(),'utf8');
 assert.match(exported,/目标：独立整理文本/);
 assert.match(exported,/- \[x\] 25 测试驱动的开发/);
 assert.match(exported,/成果自查/);
 assert.match(download.suggestedFilename(),/^selfteaching-notes-.*\.md$/);
 page.once('dialog',d=>d.dismiss());
 await page.locator('#reset-progress').click();
 assert.equal(await page.locator('#read-count').textContent(),'1');
 page.once('dialog',d=>d.accept());
 await page.locator('#reset-progress').click();
 assert.equal(await page.locator('#read-count').textContent(),'0');
 assert.equal(await page.locator('#learning-note').inputValue(),'');
 assert.equal(await page.locator('#check-progress').getAttribute('value'),'0');
 checks.push('阅读、自查与笔记刷新保存；笔记按文本处理；导出内容正确；清空取消与确认');
 await page.evaluate(key=>localStorage.setItem(key,'broken{'),key);
 await page.reload();
 assert.match(await page.locator('#save-status').textContent(),/旧记录格式无法读取/);
 assert.equal(await page.locator('.chapter').count(),46);
 const blocked=await browser.newPage();
 await blocked.addInitScript(()=>{Object.defineProperty(Storage.prototype,'getItem',{value(){throw new DOMException('blocked','SecurityError')}});Object.defineProperty(Storage.prototype,'setItem',{value(){throw new DOMException('blocked','SecurityError')}})});
 await blocked.goto(url);
 assert.match(await blocked.locator('#save-status').textContent(),/无法保存/);
 await blocked.locator('[data-route="builder"]').click();
 assert.equal(await blocked.locator('#route-title').textContent(),routes.builder.name);
 await blocked.locator('#learning-note').fill('临时笔记');
 const blockedDownload=blocked.waitForEvent('download');
 await blocked.locator('#export-notes').click();
 assert.match(await readFile(await (await blockedDownload).path(),'utf8'),/临时笔记/);
 await blocked.close();
 checks.push('损坏记录恢复；存储被禁用时仍可切换路线、记录和导出');
 await page.goto(url);
 await page.evaluate(key=>localStorage.removeItem(key),key);
 await page.reload();
 const localLinks=await page.locator('a').evaluateAll(as=>as.map(a=>a.href).filter(h=>h.startsWith(location.origin)));
 for(const href of new Set(localLinks)){
  const parsed=new URL(href),base=new URL(url);
  if(parsed.pathname===base.pathname&&parsed.hash){assert.ok(await page.locator(parsed.hash).count(),href);continue}
  if(parsed.pathname===base.pathname)continue;
  assert.equal((await page.request.get(href)).status(),200,href);
 }
 checks.push('所有本地文档、证据与章节锚点存在');
 for(const width of [1440,1024,900,768,390,320]){
  await page.setViewportSize({width,height:900});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'overflow '+width);
  await page.locator('[data-route="builder"]').click();
  assert.equal(await page.locator('#route-title').textContent(),routes.builder.name);
  await page.locator('[data-route="beginner"]').click();
 }
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>scrollTo(0,0));
 if(capture)await page.screenshot({path:path.join(root,'assets/mobile.png')});
 checks.push('1440/1024/900/768/390/320px 无横向溢出且路线可操作');
 const nojs=await browser.newPage({javaScriptEnabled:false});
 await nojs.goto(url);
 assert.equal(await nojs.locator('.chapter').count(),46);
 assert.equal(await nojs.locator('noscript').isVisible(),true);
 assert.equal(await nojs.locator('.lane').count(),3);
 assert.equal(await nojs.locator('#search').isVisible(),false);
 await nojs.locator('#chapter-25 summary').click();
 assert.equal(await nojs.locator('#chapter-25 .chapter-body').isVisible(),true);
 await nojs.close();
 checks.push('禁用 JavaScript 后正文、全部章节、原文链接及手动展开可用');
 assert.deepEqual(errors,[]);
 await writeFile(path.join(root,'notes/evidence',record),JSON.stringify({
  checkedAt:new Date().toISOString(),url,browser:'Microsoft Edge / Playwright',checks,errors,
  scope:'所列 URL 的静态网页及交互；原书 Notebook 未运行，外部链接未逐项请求，学习效果未验证'
 },null,2)+'\n');
 console.log(JSON.stringify({passed:true,checks,errors},null,2));
}finally{await browser.close()}
