// Optional browser QA; needs Playwright and Microsoft Edge (or CHROME_PATH).
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const moduleName = process.env.PLAYWRIGHT_MODULE;
const { chromium } = await import(moduleName ? pathToFileURL(moduleName).href : 'playwright');
const here = dirname(fileURLToPath(import.meta.url));
const project = resolve(here, '..');
const url = process.argv[2] ?? 'http://127.0.0.1:8765/projects/001-understand-anything/demo/';
const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : { channel: 'msedge' }) });
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 }, deviceScaleFactor: 1 });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
try {
  await page.goto(url);
  assert.equal(await page.locator('#gallery-page').isVisible(), true);
  assert.equal(await page.locator('[data-gallery-entry]').count(),12);
  await page.locator('.gallery-native').evaluate(img=>img.decode());
  await page.screenshot({path:resolve(project,'assets/gallery.png'),fullPage:true});
  checks.push('默认图谱展厅与十二个效果条目');
  for(const [cat,count] of Object.entries({code:6,domain:2,knowledge:1,design:1,helper:2,all:12})) {
    await page.locator(`[data-gallery-filter="${cat}"]`).click();
    assert.equal(await page.locator('[data-gallery-entry]').count(),count);
  }
  checks.push('四大图谱类别及辅助效果筛选');
  for(const id of ['architecture','dependencies','calls','types','data','infra','domains','steps','wiki','figma','impact','tour']) {
    await page.locator(`[data-gallery-entry="${id}"]`).click();
    const native=page.locator('.gallery-native');
    if(await native.count()) {await native.evaluate(img=>img.decode());assert.equal(await native.evaluate(img=>img.naturalWidth),1500);}
    await page.locator('[data-gallery-mode="diagram"]').click();
    const node=page.locator('[data-sample-node]').first();
    await node.focus();await page.keyboard.press('Enter');
    assert.match(await page.locator('#sample-node-info').textContent(),/关联：/);
    assert.equal(await page.locator('#gallery-focus .gallery-explanation a[target="_blank"]').count(),1);
  }
  checks.push('十二种效果切换、原版图片、示意节点键盘操作与源码入口');
  await page.locator('.relation-details summary').click();
  assert.equal(await page.locator('#relation-families tr').count(),9);
  const relationTypes=await page.locator('#relation-families td:nth-child(2)').allTextContents();
  assert.equal(new Set(relationTypes.flatMap(text=>text.split(' · '))).size,38);
  await page.locator('.relation-details summary').click();
  checks.push('完整九类三十八种关系清单');
  await page.locator('[data-gallery-entry="domains"]').click();
  await page.locator('.gallery-native').evaluate(img=>img.decode());
  await page.screenshot({path:resolve(project,'assets/gallery-domain-page.png'),fullPage:true});
  await page.locator('[data-page=effects]').click();
  assert.equal(await page.locator('#effects-page').isVisible(), true);
  assert.equal(await page.locator('.effect-choice').count(), 3);
  for (let i = 0; i < 3; i++) {
    await page.locator(`[data-effect="${i}"]`).click();
    await page.locator('#effect-image').evaluate(img => img.decode());
    assert.ok(await page.locator('#effect-image').evaluate(img => img.naturalWidth === 1500));
    assert.equal(await page.locator(`[data-effect="${i}"]`).getAttribute('aria-pressed'), 'true');
  }
  checks.push('原版效果页与三张原版 Dashboard 截图切换');
  await page.locator('[data-effect="0"]').click();
  await page.locator('#effect-image').evaluate(img => img.decode());
  await page.screenshot({ path: resolve(project, 'assets/experience.png'), fullPage: true });
  await page.locator('[data-question="2"]').click();
  assert.match(await page.locator('#example-answer').textContent(), /没有访问数据库/);
  await page.locator('[data-question="1"]').click();
  await page.locator('#example-answer [data-path="src/payment.ts"]').click();
  assert.equal(await page.locator('#details h3').textContent(), 'chargePayment');
  assert.equal(await page.locator('#impact').inputValue(), 'src/payment.ts');
  checks.push('预写示例切换及从解读跳转到真实节点');
  await page.locator('[data-page=scenarios]').click();
  for (let i = 0; i < 5; i++) {
    await page.locator(`[data-scenario="${i}"]`).click();
    assert.equal(await page.locator('#scenario-detail li').count(), 3);
  }
  await page.locator('[data-scenario="1"]').click();
  await page.screenshot({ path: resolve(project, 'assets/scenarios.png'), fullPage: true });
  await page.locator('#scenario-action').click();
  assert.equal(await page.locator('#impact').inputValue(), 'src/payment.ts');
  checks.push('五个场景的操作路线与评审场景跳转');
  await page.locator('[data-page=guide]').click();
  for (const platform of ['codex-win', 'codex-unix', 'claude', 'cursor']) {
    await page.locator('#platform').selectOption(platform);
    assert.equal(await page.locator('.guide-step').count(), 5);
    const expected = platform.startsWith('codex') ? '$understand --language zh' : '/understand --language zh';
    assert.equal(await page.locator('#command-1').textContent(), expected);
    assert.match(await page.locator('#command-2').textContent(), /understand-dashboard/);
  }
  await page.locator('#platform').selectOption('codex-win');
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.locator('[data-copy="1"]').click();
  await page.getByText('已复制命令', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), '$understand --language zh');
  await page.screenshot({ path: resolve(project, 'assets/guide.png'), fullPage: true });
  checks.push('四种工具配置、五步使用流程与复制命令');
  await page.getByText('只想让同事查看图谱', { exact: true }).click();
  assert.equal(await page.locator('.viewer-command').isVisible(), true);
  await page.reload();
  assert.equal(await page.locator('#guide-page').isVisible(), true);
  checks.push('指南常见问题与哈希刷新');
  await page.goto(url + '#graph');
  await page.getByRole('heading', { name: '订单流程图谱', exact: true }).waitFor();
  assert.equal(await page.locator('#graph [role=button]').count(), 6);
  assert.equal(await page.locator('#node-count').textContent(), '12');
  checks.push('初始图谱与统计');
  await page.getByRole('button', { name: '查看 reserveStock', exact: true }).click();
  assert.equal(await page.locator('#details h3').textContent(), 'reserveStock');
  assert.match(await page.locator('#details .code').textContent(), /quantity <= 100/);
  checks.push('节点点击、真实源代码与行号');
  await page.getByRole('searchbox').fill('chargePayment');
  assert.equal(await page.locator('#graph [role=button]').count(), 1);
  await page.getByRole('searchbox').fill('not-found-xyz');
  assert.equal(await page.locator('#empty').isVisible(), true);
  await page.getByRole('button', { name: '清除筛选', exact: true }).click();
  checks.push('筛选、空状态与恢复');
  await page.getByRole('button', { name: '文件', exact: true }).click();
  assert.equal(await page.locator('#graph [role=button]').count(), 6);
  await page.getByRole('button', { name: '查看 orders.ts', exact: true }).click();
  assert.equal(await page.locator('#details .relation').count(), 4);
  await page.locator('#impact').selectOption('src/payment.ts');
  assert.match(await page.locator('#impact-status').textContent(), /已改动 2 · 一跳关联 2/);
  assert.equal(await page.locator('#graph rect[fill="#fff3ec"]').count(), 1);
  assert.equal(await page.locator('#graph rect[fill="#fffae9"]').count(), 1);
  checks.push('文件视图与上游一跳影响结果');
  await page.locator('#impact').selectOption('');
  await page.getByRole('button', { name: '下一步', exact: true }).click();
  assert.equal(await page.locator('#details h3').textContent(), 'reserveStock');
  await page.getByRole('button', { name: '上一步', exact: true }).click();
  assert.equal(await page.locator('#details h3').textContent(), 'createOrder');
  checks.push('阅读导览前进与后退');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出 JSON ↓', exact: true }).click();
  const download = await downloadPromise;
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(exported.nodes.length, 12); assert.equal(exported.edges.length, 14);
  checks.push('JSON 导出内容');
  await page.locator('[data-page=pipeline]').click();
  await page.locator('[data-step="6"]').click();
  assert.match(await page.locator('#pipeline-detail').textContent(), /COSMETIC/);
  await page.reload();
  assert.equal(await page.locator('#pipeline-page').isVisible(), true);
  checks.push('原理步骤与子路径刷新');
  await page.locator('[data-page=experiments]').click();
  assert.equal(await page.locator('.check').count(), 7);
  await page.screenshot({ path: resolve(project, 'assets/experiments.png'), fullPage: true });
  await page.locator('[data-page=capabilities]').click();
  assert.equal(await page.locator('#capability-rows tr').count(), 10);
  checks.push('实验页与能力矩阵');
  await page.locator('[data-page=graph]').click();
  await page.getByRole('button', { name: '查看 createOrder', exact: true }).focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#details h3').textContent(), 'createOrder');
  await page.locator('#search').focus();
  await page.locator('#search').blur();
  await page.screenshot({ path: resolve(project, 'assets/cover.png'), fullPage: true });
  checks.push('键盘节点操作与桌面截图');
  await page.setViewportSize({ width: 390, height: 844 });
  for (const view of ['gallery', 'compare', 'effects', 'scenarios', 'guide', 'graph', 'pipeline', 'experiments', 'capabilities']) {
    await page.locator(`[data-page=${view}]`).click();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `Mobile overflow: ${view}`);
  }
  await page.locator('[data-page=graph]').click();
  await page.screenshot({ path: resolve(project, 'assets/mobile.png'), fullPage: true });
  await page.locator('[data-page=effects]').click();
  await page.locator('#effect-image').evaluate(img => img.decode());
  await page.screenshot({ path: resolve(project, 'assets/experience-mobile.png'), fullPage: true });
  await page.locator('[data-page=gallery]').click();
  await page.locator('[data-gallery-entry="architecture"]').click();
  await page.locator('.gallery-native').evaluate(img=>img.decode());
  await page.screenshot({path:resolve(project,'assets/gallery-mobile.png'),fullPage:true});
  checks.push('390px 移动端九个视图无页面横向溢出');
  await page.goto(url + '#constructor');
  assert.equal(await page.locator('#gallery-page').isVisible(), true);
  checks.push('未知哈希安全回退到图谱展厅首页');
  await page.goto(pathToFileURL(resolve(project, 'demo/index.html')).href + '#graph');
  assert.equal(await page.locator('#graph [role=button]').count(), 6);
  checks.push('file:// 直接打开，不依赖后端');
  await page.locator('[data-page=effects]').click();
  await page.locator('#effect-image').evaluate(img => img.decode());
  assert.ok(await page.locator('#effect-image').evaluate(img => img.naturalWidth > 0));
  checks.push('file:// 下效果页面本地图片可用');
  await page.locator('[data-page=gallery]').click();
  await page.locator('[data-gallery-filter="design"]').click();
  await page.locator('.gallery-native').evaluate(img=>img.decode());
  assert.equal(await page.locator('.gallery-native').evaluate(img=>img.naturalWidth),1500);
  checks.push('file:// 图谱分类与设计效果图片可用');
  assert.deepEqual(errors, []);
  const result = { generatedAt: new Date().toISOString(), browser: await browser.version(), desktop: '1600x1100', mobile: '390x844', checks, browserErrors: errors, scope: '独立研究展示页面；不是上游 Dashboard 端到端验证' };
  await writeFile(resolve(project, 'notes/evidence/browser-qa.json'), JSON.stringify(result, null, 2) + '\n');
  console.log(JSON.stringify(result, null, 2));
} finally { await browser.close(); }
